BUG: ConstraintSet crash on API < 19
Steps:

1. Open constraintlayout app on device with API 17
2. Click Constraint Set example

App is crashin with:

java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3